apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    dependOn: gin-server-skeleton
  name: gin-server-skeleton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-server-skeleton
  template:
    metadata:
      labels:
        app: gin-server-skeleton
    spec:
      initContainers:
      - name: wait-for-onezone
        image: roandocker/k8s-wait-for:1.0.0
        imagePullPolicy: IfNotPresent
        args:
          - "pod"
          - "app=mariadb"
      containers:
      - name: gin-server-skeleton
        env:
        - name: DB_HOST
          value: mariadb
        - name: DB_PORT
          value : "3306"
        - name: DB_USER
          value: root
        - name: DB_PASSWD
          value: root123
        - name: DB_DATABASE
          value: gin_scaffold
        - name: DB_LOGMODE
          value: "true"
        image: roandocker/gin-server-skeleton:latest
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          tcpSocket:
            port: 8080
          timeoutSeconds: 3
          failureThreshold: 30
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          tcpSocket:
            port: 8080
          timeoutSeconds: 3
          failureThreshold: 30
        resources:
          limits:
            cpu: 150m
            memory: 680Mi
          requests:
            cpu: 50m
            memory: 256Mi
      enableServiceLinks: false
---
apiVersion: v1
kind: Service
metadata:
  name: gin-server-skeleton
spec:
  ports:
  - name: "http-8080"
    port: 8080
    targetPort: 8080
  selector:
    app: gin-server-skeleton
  type: ClusterIP
status:
  loadBalancer: {}
...