---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  serviceName: "mariadb"
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      enableServiceLinks: false
      containers:
      - name: mariadb
        image: mariadb:10.4
        ports:
        - containerPort: 3306
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "100m"
            memory: "512Mi"
        env:
        - name: MYSQL_ROOT_USER
          value: root
        - name: MYSQL_ROOT_PASSWORD
          value: ""
        - name: MYSQL_USER
          value: zhuiyi
        - name: MYSQL_PASSWORD
          value: ""
        - name: MYSQL_DATABASE
          value: zhuiyi
        - name: TZ
          value: Asia/Shanghai
# service
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  type: NodePort
  ports:
  - name: "3306"
    port: 3306
    nodePort: 30306


...




